stages:
  - Trigger

test_nuttx:
  stage: Trigger
  trigger:
    project: idf/apache/incubator-nuttx
    strategy: depend
  allow_failure: true
  variables:
    PARENT_ESP_HAL_3RDPARTY_BRANCH: ${CI_COMMIT_BRANCH}
